/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.salusa.dyemixer;

public class App {
    public static void main(String[] args) {
        final AppletFrame frame = new AppletFrame();
    }
}
