/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.salusa.dyemixer;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        // NOP for now
    }
}
